#!/usr/bin/make -f

KERNEL_VERSION_FULL ?= $(shell uname -sr)
KERNEL_VERSION_NUMBER ?= $(shell uname -r)
KERNEL_SOURCE ?= /lib/modules/$(shell uname -r)/build
MODULE_PATH ?= $(DESTDIR)/lib/modules/$(KERNEL_VERSION_NUMBER)/kernel/drivers/char/joystick

all:
	$(CC) -D__KERNEL__ -I$(KERNEL_SOURCE)/include -Wall -Wstrict-prototypes -Wno-trigraphs -O2 -fomit-frame-pointer -fno-strict-aliasing -fno-common -pipe -mpreferred-stack-boundary=2 -falign-functions=4 -DMODULE -DMODVERSIONS -include $(KERNEL_SOURCE)/include/linux/modversions.h -c ddrmat.c

install:
	install -D -m 644 ddrmat.o $(MODULE_PATH)/ddrmat.o
	@echo "Be sure to run depmod -ae."

clean:
	rm -f *~ *.o
